<?php
/*
* Plugin Name: ManageAm Mobile App
* Description: Manageam Mobile application inteface integration with website
* Version: 1.0
* Author: Adelodun Damilare
* Author URI: https://about.me/adelodundamilare
* License: MIT
* Text Domain: manageam mobile app
*/


/* ==================================================
  Create ManageAm User Post Type
  ================================================== */
if (!defined('ABSPATH'))
    exit; // Exit if accessed directly
add_action('init', 'manageam_user_post_type');
if( !function_exists( 'manageam_user_post_type' ) ){
        function manageam_user_post_type() {
        $labels = array(
            'name' => __('ManageAm Users', 'framework'),
            'singular_name' => __('ManageAm User', 'framework'),
            'all_items'=> __('ManageAm Users', 'framework'),
            'add_new' => __('Add New', 'framework'),
            'add_new_item' => __('Add New ManageAm User', 'framework'),
            'edit_item' => __('Edit ManageAm User', 'framework'),
            'new_item' => __('New ManageAm User', 'framework'),
            'view_item' => __('View ManageAm User', 'framework'),
            'search_items' => __('Search ManageAm User', 'framework'),
            'not_found' => __('No ManageAm User have been added yet', 'framework'),
            'not_found_in_trash' => __('Nothing found in Trash', 'framework'),
            'parent_item_colon' => ''
        );
        $args = array(
            'labels' => $labels,

            /**
             * this codes disable add new functionality, which means
             * admin cannot create users manually
             */
            
            // 'capability_type' => 'custom_post_type',
            // 'capabilities' => array(
            //     'create_posts' => false
            // ),

            // normal code continues
            'menu_icon' => 'dashicons-groups',
            'capability_type' => 'page',
            'public' => true,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_nav_menus' => false,
            'rewrite' => false,
            'supports' => array(''),
            'has_archive' => true,
        );
        register_post_type('manageam_user', $args);
    }
}

// managam user custom post fields
add_filter( 'manage_edit-manageam_user_columns', 'manageam_user_columns' );
if( !function_exists('manageam_user_columns') ){
        function manageam_user_columns( $columns ) {

        $columns = array(
            'cb' => '<input type="checkbox" />',
            'manageam_user_id' => __( 'ID' ),
            'manageam_user_email' => __( 'Email' ),
            'manageam_user_password' => __( 'Password' ),
            'manageam_user_dwalk_status' => __( 'D-Walk Status' ),
            'manageam_user_dwalk_code' => __( 'D-Walk Code' ),
            'date' => __( 'Date' )
        );

        return $columns;
    }
}

// add contents to custom post fields
add_action( 'manage_manageam_user_posts_custom_column', 'manageam_user_fill_columns', 10, 2 );
if( !function_exists( 'manageam_user_fill_columns' ) ){
        function manageam_user_fill_columns( $column, $post_id ){
        switch( $column ) {
            // for autogenerated user id
            case 'manageam_user_id':
            
            if ( empty( $post_id ) ){ echo __( 'Unknown' ); }
            else{ echo __( $post_id ); }
            
            break;
            
            // for inputed user email
            case 'manageam_user_email':
            
            $manageam_email_value = get_post_meta( $post_id, '_manageam_email_value', true );
            if ( empty( $manageam_email_value ) ){ echo __( 'Unknown' ); }
            else{ echo __( $manageam_email_value ); }
            
            break;
            
            // for inputed manageam user password
            case 'manageam_user_password':
            
            $manageam_password_value = get_post_meta( $post_id, '_manageam_password_value', true );
            if ( empty( $manageam_password_value ) ){ echo __( 'Unknown' ); }
            else{ echo __( $manageam_password_value ); }
            
            break;
            
            // for calculated manageam user diabetes walk status
            case 'manageam_user_dwalk_status':
            
            $manageam_dwalk_status_value = get_post_meta( $post_id, '_manageam_dwalk_status_value', true );
            if ( empty( $manageam_dwalk_status_value ) ){ echo __( '' ); }
            else{ echo __( $manageam_dwalk_status_value ); }
            
            break;
            
            // for autogenerated manageam user dwalk code
            case 'manageam_user_dwalk_code':

            $manageam_dwalk_code_value = get_post_meta( $post_id, '_manageam_dwalk_code_value', true );
            if ( empty( $manageam_dwalk_code_value ) ){ echo __( '' ); }
            else{ echo __( $manageam_dwalk_code_value ); }

            break;
        }
    }
}

// making custom post fields sortable
add_filter( 'manage_edit-manageam_user_sortable_columns', 'manageam_user_sortable_columns' );
if( !function_exists( 'manageam_user_sortable_columns' ) ){
    function manageam_user_sortable_columns( $columns ) {

        $columns['manageam_user_id'] = 'manageam_user_id';
        $columns['manageam_user_email'] = 'manageam_user_email';
        $columns['manageam_user_dwalk_status'] = 'manageam_user_dwalk_status';

        return $columns;
    }
}

// making custom post field filterable
add_action( 'load-edit.php', 'manageam_user_filter' );

if( !function_exists('manageam_user_filter') ){
    function manageam_user_filter() {
        add_filter( 'request', 'filter_manageam_user' );
    }
}

if( !function_exists( 'filter_manageam_user' ) ){
    function filter_manageam_user( $vars ) {

        /* Check if we're viewing the 'manageam_user_dwalk_status' post type. */
        if ( isset( $vars['post_type'] ) && 'manageam_user_dwalk_status' == $vars['post_type'] ) {

            $vars = array_merge(
                $vars,
                array(
                    'meta_key' => 'manageam_user_dwalk_status',
                    'orderby' => 'DESC'
                )
            );
        }

        return $vars;
    }
}


/**
 * Add meta boxes
 */

add_action('add_meta_boxes', 'manageam_user_id_meta_box');

if( !function_exists( 'manageam_user_id_meta_box' ) ){
    function manageam_user_id_meta_box(){
        add_meta_box(
                'manageam_user_id_meta_box_id',           // Unique ID
                'ManageAm User Info',  // Box title
                'manageam_user_id_meta_box_cb',  // Content callback, must be of type callable
                'manageam_user'                   // Post type
            );
    }
}

if( !function_exists( 'manageam_user_id_meta_box_cb' ) ){
    function manageam_user_id_meta_box_cb($post) {
    
        wp_nonce_field( basename( __FILE__ ), 'manageam_user_nonce' );
    
        $manageam_email_value = get_post_meta( $post->ID, '_manageam_email_value', true );
        $manageam_password_value = get_post_meta( $post->ID, '_manageam_password_value', true );
        $manageam_dwalk_status_value = get_post_meta( $post->ID, '_manageam_dwalk_status_value', true );
        $manageam_dwalk_code_value = get_post_meta( $post->ID, '_manageam_dwalk_code_value', true );

        echo '<table class="form-table editcomment">';
        echo '<tbody>';
        
        echo '<tr>';
        echo '<td style="width:100px"><label for="manageam_user_email_cs">Email:</label></td>';
        echo '<td><input style="width:98%" type="text" name="manageam_email_value" size="30" value="'. $manageam_email_value .'" id="manageam_user_email_cs"></td>';
        echo '</tr>';
        
        echo '<tr>';
        echo '<td style="width:100px"><label for="manageam_user_password_cs">Password:</label></td>';
        echo '<td><input style="width:98%" type="text" name="manageam_password_value" size="30" value="'. $manageam_password_value .'" id="manageam_user_password_cs"></td>';
        echo '</tr>';
        
        echo '<tr>';
        echo '<td style="width:100px"><label for="manageam_user_d_walk_status_cs">D-Walk Status:</label></td>';
        echo '<td><input style="width:98%" type="text" name="manageam_dwalk_status_value" size="30" value="'. $manageam_dwalk_status_value .'" id="manageam_user_d_walk_status_cs"></td>';
        echo '</tr>';
        
        echo '<tr>';
        echo '<td style="width:100px"><label for="manageam_user_d_walk_code_cs">D-Walk Code:</label></td>';
        echo '<td><input style="width:98%" type="text" name="manageam_dwalk_code_value" size="30" value="'. $manageam_dwalk_code_value .'" id="manageam_user_d_walk_code_cs"></td>';
        echo '</tr>';

        echo '</tbody>';
        echo '</table>';
    }
}

// saving custom fields
add_action( 'save_post_manageam_user', 'manageam_user_save_meta_boxes_data', 10, 2 );

if( !function_exists( 'manageam_user_save_meta_boxes_data' ) ){
    function manageam_user_save_meta_boxes_data( $post_id ){

        if ( !isset( $_POST['manageam_user_nonce'] ) || !wp_verify_nonce( $_POST['manageam_user_nonce'], basename( __FILE__ ) ) ){
            return;
        }

        if ( ! current_user_can( 'edit_post', $post_id ) ){
            return;
        }

        if ( isset( $_REQUEST['manageam_email_value'] ) ) {
            update_post_meta( $post_id, '_manageam_email_value', sanitize_email( $_POST['manageam_email_value'] ) );
        }

        if ( isset( $_REQUEST['manageam_password_value'] ) ) {
            update_post_meta( $post_id, '_manageam_password_value', sanitize_text_field( $_POST['manageam_password_value'] ) );
        }

        if ( isset( $_REQUEST['manageam_dwalk_status_value'] ) ) {
            update_post_meta( $post_id, '_manageam_dwalk_status_value', sanitize_text_field( $_POST['manageam_dwalk_status_value'] ) );
        }

        if ( isset( $_REQUEST['manageam_dwalk_code_value'] ) ) {
            update_post_meta( $post_id, '_manageam_dwalk_code_value', sanitize_text_field( $_POST['manageam_dwalk_code_value'] ) );
        }

    }
}

// WORDPRESS REST API EXTENSION
add_action( 'rest_api_init', function () {
    register_rest_route(
        'manageam/v1', '/register',
        array(
            'methods' => ['GET', 'POST', 'PUT', 'PATCH'],
            'callback' => 'register_new_manageam_user',
            )
        );
    }
);

if( !function_exists( 'register_new_manageam_user' ) ){

    function register_new_manageam_user( WP_REST_Request $request ) {
        // $param = $request->get_param( 'some_param' );
        // return $param;

        if(isset($_POST['register_email']) && isset($_POST['register_password'])){

            // get posted values
            $email = $_POST['register_email'];
            $password = $_POST['register_password'];
            $d_walk_status = '';
            $d_walk_code = '';

            // check if user is already existed with the same email
            if (userAlreadyExisted($email)) {
                // user already existed
                $response["error"] = TRUE;
                $response["error_msg"] = "User already exist";
                echo json_encode($response);
            }else {
                // post and save values to manageam_user custom post type
                sendWelcomeMessage($email);
                $response["error"] = FALSE;
                $response["email"] = storeNewManageAmUser($email, $password);
                $response["message"] = "New user account created successfully";
                echo json_encode($response);
            }

        }
    }
}

// WORDPRESS LOGIN REST API
add_action( 'rest_api_init', function () {
    register_rest_route(
        'manageam/v1', '/login',
        array(
            'methods' => ['GET', 'POST'],
            'callback' => 'login_manageam_user',
            )
        );
    }
);

if( !function_exists('login_manageam_user') ){

    function login_manageam_user(){

        if(isset($_POST['login_email']) && isset($_POST['login_password']) ){

            $login_email = $_POST['login_email'];
            $login_password = $_POST['login_password'];

            // get the user by email and password
            $user = manageam_getUserByEmailAndPassword($login_email, $login_password);
            
            if ($user != false) {
                // use is found
                $response["error"] = FALSE;
                $response["err_msg"] = "Success!, you are now loged in";
                echo json_encode($response); // this should change
            } else {
                // user is not found with the credentials
                $response["error"] = TRUE;
                $response["err_msg"] = "Login credentials are wrong. Please try again!";
                echo json_encode($response);
            }

        }

    }

}

// WORDPRESS UPDATE D WALK
add_action( 'rest_api_init', function () {
    register_rest_route(
        'manageam/v1', '/updatedwalk',
        array(
            'methods' => ['GET', 'POST'],
            'callback' => 'update_manageam_user',
            )
        );
    }
);

if( !function_exists('update_manageam_user') ){

    function update_manageam_user(){

        if(isset($_POST['update_email']) && isset($_POST['user_value']) ){

            $user_email = $_POST['update_email'];
            $user_value = $_POST['user_value'];

            // get the user by email and password
            $user = userAlreadyExisted($user_email);
            
            if ($user != false) {

                $saveDiabetesWalk = updateDiabetesValue($user_email, $user_value);

                if($saveDiabetesWalk){
                    // use is found
                    $response["error"] = FALSE;
                    $response["err_msg"] = "Success, you are now signed up for diabetes walk";
                    echo json_encode($response); // this should change
                }
            } else {
                // user is not found with the credentials
                $response["error"] = TRUE;
                $response["err_msg"] = "Invalid user!";
                echo json_encode($response);
            }

        }else{
            echo json_decode("invalid input");
        }

    }

}

// CHECK IF USER ALREADY EXIST
if(!function_exists('userAlreadyExisted')){
    function userAlreadyExisted($email) {

        $theposts = get_posts(
            array(
                'post_type' => 'manageam_user',
                'meta_query' => array(
                array(
                    'key' => '_manageam_email_value',
                    'value' => $email,
                    'compare' => '='
                    )
                )
            )
        );

        if($theposts){
            return true;
        }else{
            return false;
        }
        
    }
}

// STORE NEW USER
if(!function_exists( 'storeNewManageAmUser' )){
    function storeNewManageAmUser($email, $password) {
        
        $encrypted_password = password_hash($password, PASSWORD_DEFAULT); // encrypted password

        $post_id = wp_insert_post(
            array(
                'comment_status'	=>	'closed',
                'ping_status'		=>	'closed',
                'post_status'		=>	'publish',
                'post_type'		=>	'manageam_user'
            )
        );
        update_post_meta($post_id, '_manageam_email_value', $email);
        update_post_meta($post_id, '_manageam_password_value', $encrypted_password);
        update_post_meta($post_id, '_manageam_dwalk_status_value', $d_walk_status);
        update_post_meta($post_id, '_manageam_dwalk_code_value', $d_walk_code);

        return true;

    }
}

// STORE NEW USER
if(!function_exists( 'updateDiabetesValue' )){
    function updateDiabetesValue($email, $value) {

        $post_id = wp_update_post(
            array(
                'comment_status'	=>	'closed',
                'ping_status'		=>	'closed',
                'post_status'		=>	'publish',
                'post_type'		=>	'manageam_user'
            )
        );

        $theposts = get_posts(
            array(
                'post_type' => 'manageam_user',
                'meta_query' => array(
                array(
                    'key' => '_manageam_email_value',
                    'value' => $email,
                    'compare' => '='
                    )
                )
            )
        );

        if($theposts){
            $posts = $theposts[0];
            $d_walk_status = 'Registered';
            $d_walk_code = 'MDW18-' . mt_rand(1000, 9999);

            
            sendDiabetesWalkRegisteredMessage($email, $value, $d_walk_code);
        
            $my_post_id = $theposts[0]->ID;
            update_post_meta($my_post_id, '_manageam_dwalk_status_value', $d_walk_status);
            update_post_meta($my_post_id, '_manageam_dwalk_code_value', $d_walk_code);

            return true;

        }else{
            return false;
        }

    }
}

// GET USER EMAIL BY PASSWORD
if(!function_exists( 'manageam_getUserByEmailAndPassword' )){
    function manageam_getUserByEmailAndPassword($email, $password) {
        
        $theposts = get_posts(
            array(
                'post_type' => 'manageam_user',
                'meta_query' => array(
                array(
                    'key' => '_manageam_email_value',
                    'value' => $email,
                    'compare' => '='
                    )
                )
            )
        );
                
        $saved_password = '';
        foreach($theposts as $post){
            $saved_password = get_post_meta( $post->ID, '_manageam_password_value', true );
        }
        
        if( password_verify($password, $saved_password) ){
            return true;
        }

        return false;
        
    }
}

if(!function_exists('sendWelcomeMessage')){
    function sendWelcomeMessage($email)
    {
        $message = '
        <table width="100%" bgcolor="#011e3e" cellpadding="0" ; cellspacing="0">
    <tbody>
        <tr>
            <td>
                <table style="width:100%; max-width: 500px; margin: 100px auto;">
                    <tbody>
                        <tr>
                            <td>
                                <table style="width:100%;">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <h1 style="text-align: center;color:white; font-family:Helvetica Neue, Arial;">
                                                    <img style="width:200px" src="http://sh-ei.org/wp-content/uploads/2018/05/manageam-white-loved-logo.png" alt="ManageAm Logo">
                                                </h1>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="width:100%; background-color:white;color:#333;padding: 32px">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <table>
                                                    <tbody>
                                                        <tr>
                                                            <td style="text-align:left">
                                                                <h2 style="font-family:Helvetica Neue, Arial; font-size: 14px; color:#333;line-height:1.2">
                                                                    Hello,
                                                                    <br />
                                                                    <br /> Thank you for signing up with ManageAm.
                                                                    <br />
                                                                    ManageAm is a unique tool developed to make Diabetes education and self management easier for you.<br /><br />
                                                                    <br />With ManageAm app, users can now track and
                                                                    record every part of their daily routine in order to
                                                                    live a healthier life. 
                                                                    <br />
                                                                    <br /> Thank you,
                                                                    <br />
                                                                    <br /> SHEI
                                                                    <br />
                                                                    <a href="http://sh-ei.org" style="color:inherit">www.sh-ei.org</a>


                                                                </h2>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="width:100%;">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <p style="text-align: center;color:white; font-family:Helvetica Neue, Arial;font-weight:bold; font-size: 12px;margin-top: 24px">
                                                    This message is an automated message from
                                                    <a href="http://www.sh-ei-org" style="color:white">www.sh-ei.org</a>
                                                </p>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
        ';

        $subject = 'Welcome to ManageAm';
        $to = $email;
        
        $headers = "From: contact@sh-ei.org\r\n";
        $headers .= "Reply-To: \r\n";
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=UTF-8\r\n";

        try{
            wp_mail($to, $subject, $message, $headers);
        }catch(Exception $e){

        }
        
        return true;
    }
}

if(!function_exists('sendDiabetesWalkRegisteredMessage')){
    function sendDiabetesWalkRegisteredMessage($email, $value, $reg_number) {
        
        $newValue = explode(",", $value);
        $name = '';
        $location = '';

        if(count($newValue) > 0){
            $location = $newValue[0];
            $name = $newValue[1];
        }

        $message = '
        <table width="100%" bgcolor="#011e3e" cellpadding="0" ; cellspacing="0">
    <tbody>
        <tr>
            <td>
                <table style="width:100%; max-width: 500px; margin: 100px auto;">
                    <tbody>
                        <tr>
                            <td>
                                <table style="width:100%;">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <h1 style="text-align: center;color:white; font-family:Helvetica Neue, Arial;">
                                                    <img style="width:200px" src="http://sh-ei.org/wp-content/uploads/2018/05/manageam-white-loved-logo.png" alt="ManageAm Logo">
                                                </h1>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="width:100%; background-color:white;color:#333;padding: 32px">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <table>
                                                    <tbody>
                                                        <tr>
                                                            <td style="text-align:left">
                                                                <h2 style="font-family:Helvetica Neue, Arial; font-size: 14px; color:#333;line-height:1.2">
                                                                    Hello,
                                                                    <br />
                                                                    <br /> Thank you for downloading ManageAm and completing your registration for ManageAm Diabetes Walk. Please find below information as submitted and your registration number for the walk
                                                                    <br />
                                                                    <br /> 
                                                                    Name: <span style="color:#dbb919">'. $name .'</span><br />
                                                                    Location: <span style="color:#dbb919">'. $location .'</span><br />
                                                                    Registration No: <span style="color:#dbb919">'. $reg_number .'</span>
                                                                    <br />
                                                                    <br /> Thank you,
                                                                    <br />
                                                                    <br /> SHEI
                                                                    <br />
                                                                    <a href="http://sh-ei.org" style="color:inherit">www.sh-ei.org</a>


                                                                </h2>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="width:100%;">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <p style="text-align: center;color:white; font-family:Helvetica Neue, Arial;font-weight:bold; font-size: 12px;margin-top: 24px">
                                                    This message is an automated message from
                                                    <a href="http://www.sh-ei-org" style="color:white">www.sh-ei.org</a>
                                                </p>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
        ';

        $subject = 'ManageAm Diabetes Walk 2018';
        $to = $email;
        
        $headers = "From: contact@sh-ei.org\r\n";
        $headers .= "Reply-To: \r\n";
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=UTF-8\r\n";

        try{
            wp_mail($to, $subject, $message, $headers);
        }catch(Exception $e){

        }
        
        return true;
    }
}